name: 'build-push'
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: 'true'
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - shell: bash
        run:
          mvn --batch-mode --update-snapshots package
