name: 'build-push'
on:
  push:
    branches:
      - main
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: 'true'
      - shell: bash
        run:
          ifconfig
